# wiki = alacritty.org/config-alacritty.html

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
size = 16

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true
thickness = 0.1

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"
opacity = 1
dimensions = { columns = 110, lines = 35 }
padding = { x = 10, y = 10 }

[mouse]
hide_when_typing = true

[general]
live_config_reload = true
import = [ "/home/maxelonej/.config/alacritty/kanagawa-dragon.toml" ]
